# Data Visualisation

## Import the required libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
print("libraries imported")

libraries imported

## Importing the training and test data-set cleaned csv files

In [2]:
train_cleaned = pd.read_csv("/Users/sobil/Documents/PyCharm_Projects/PredicitiveAnalysis_Project/credit_train_cleaned.csv")
train_cleaned.head()

,Unnamed: 0,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,0,14dd8831-6af5-400b-83ec-68e61888a048,981165ec-3274-42f5-a3b4-d104041a9ca9,Fully Paid,445412.0,Short Term,709.000000,1.167493e+06,8.0,Home Mortgage,Home Improvements,5214.74,17.2,6.0,1.0,228190.0,416746.0,1.0,0.0
1,1,4771cc26-131a-45db-b5aa-537ea4ba5342,2de017a3-2e01-49cb-a581-08169e83be29,Fully Paid,262328.0,Short Term,1076.275101,1.378339e+06,10.0,Home Mortgage,Debt Consolidation,33295.98,21.1,35.0,0.0,229976.0,850784.0,0.0,0.0
2,2,4eed4e6a-aa2f-4c91-8651-ce984ee8fb26,5efb2b2b-bf11-4dfd-a572-3761a2694725,Fully Paid,99999999.0,Short Term,741.000000,2.231892e+06,8.0,Own Home,Debt Consolidation,29200.53,14.9,18.0,1.0,297996.0,750090.0,0.0,0.0
3,3,77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a,e777faab-98ae-45af-9a86-7ce5b33b1011,Fully Paid,347666.0,Long Term,721.000000,8.069490e+05,3.0,Own Home,Debt Consolidation,8741.90,12.0,9.0,0.0,256329.0,386958.0,0.0,0.0
4,4,d4062e70-befa-4995-8643-a0de73938182,81536ad9-5ccf-4eb8-befb-47a4d608658e,Fully Paid,176220.0,Short Term,1076.275101,1.378339e+06,5.0,Rent,Debt Consolidation,20639.70,6.1,15.0,0.0,253460.0,427174.0,0.0,0.0

In [3]:
train_cleaned.tail(10)

,Unnamed: 0,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
99784,99990,686017b3-dc24-4f8a-af92-0bd077452d3d,1a583add-21ba-410f-9c42-757c4ed19322,Fully Paid,99999999.0,Short Term,742.000000,1.190046e+06,NaN,Rent,other,11969.81,20.1,9.0,0.0,37392.0,134442.0,0.0,0.0
99785,99991,326d0f2b-015f-480e-90e9-9c0d7d307196,ed9a397b-8a72-45c2-92de-b91f990a623d,Fully Paid,244266.0,Short Term,714.000000,1.619047e+06,10.0,Rent,Debt Consolidation,4290.39,21.4,5.0,1.0,132012.0,242660.0,1.0,0.0
99786,99992,c568adaa-16f9-43d3-b522-8532fb57cb16,cbb29fd6-e418-4f09-a4bd-4de83428caab,Fully Paid,48796.0,Short Term,1076.275101,1.378339e+06,4.0,Home Mortgage,major_purchase,8298.63,8.3,9.0,0.0,87875.0,239404.0,0.0,0.0
99787,99993,79b81158-5d55-4766-8ad6-ebcd683f7d59,e45e8dc4-05ad-4efe-92cc-784a6d5ef61a,Fully Paid,44484.0,Short Term,717.000000,1.152426e+06,10.0,Home Mortgage,small_business,6280.64,21.0,6.0,0.0,961932.0,0.0,0.0,0.0
99788,99994,8506a4e9-af7d-47d2-a1bf-7ea2c41858f0,be67200e-1ef1-4b63-86a6-2bf27d3c704d,Fully Paid,210584.0,Short Term,719.000000,7.833890e+05,1.0,Home Mortgage,Other,3727.61,17.4,6.0,0.0,456.0,259160.0,0.0,0.0
99789,99995,3f94c18c-ba8f-45d0-8610-88a684a410a9,2da51983-cfef-4b8f-a733-5dfaf69e9281,Fully Paid,147070.0,Short Term,725.000000,4.754370e+05,7.0,Own Home,other,2202.86,22.3,5.0,0.0,47766.0,658548.0,0.0,0.0
99790,99996,06eba04f-58fc-424a-b666-ed72aa008900,77f2252a-b7d1-4b07-a746-1202a8304290,Fully Paid,99999999.0,Short Term,732.000000,1.289416e+06,1.0,Rent,Debt Consolidation,13109.05,9.4,22.0,0.0,153045.0,509234.0,0.0,0.0
99791,99997,e1cb4050-eff5-4bdb-a1b0-aabd3f7eaac7,2ced5f10-bd60-4a11-9134-cadce4e7b0a3,Fully Paid,103136.0,Short Term,742.000000,1.150545e+06,6.0,Rent,Debt Consolidation,7315.57,18.8,12.0,1.0,109554.0,537548.0,1.0,0.0
99792,99998,81ab928b-d1a5-4523-9a3c-271ebb01b4fb,3e45ffda-99fd-4cfc-b8b8-446f4a505f36,Fully Paid,530332.0,Short Term,746.000000,1.717524e+06,9.0,Rent,Debt Consolidation,9890.07,15.0,8.0,0.0,404225.0,738254.0,0.0,0.0
99793,99999,c63916c6-6d46-47a9-949a-51d09af4414f,1b3014be-5c07-4d41-abe7-44573c375886,Fully Paid,99999999.0,Short Term,743.000000,9.351800e+05,10.0,Own Home,Debt Consolidation,9118.10,13.0,4.0,1.0,45600.0,91014.0,1.0,0.0

In [8]:
train_cleaned.shape

(99794, 19)

In [5]:
test_cleaned = pd.read_csv("/Users/sobil/Documents/PyCharm_Projects/PredicitiveAnalysis_Project/credit_test_cleaned.csv")
test_cleaned.head()

,Unnamed: 0,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,0,f738779f-c726-40dc-92cf-689d73af533d,ded0b3c3-6bf4-4091-8726-47039f2c1b90,611314.0,Short Term,747.0,2074116.0,10.0,Home Mortgage,Debt Consolidation,42000.83,21.8,9.0,0.0,621908.0,1058970.0,0.0,0.0
1,1,6dcc0947-164d-476c-a1de-3ae7283dde0a,1630e6e3-34e3-461a-8fda-09297d3140c8,266662.0,Short Term,734.0,1919190.0,10.0,Home Mortgage,Debt Consolidation,36624.40,19.4,11.0,0.0,679573.0,904442.0,0.0,0.0
2,2,f7744d01-894b-49c3-8777-fc6431a2cff1,2c60938b-ad2b-4702-804d-eeca43949c52,153494.0,Short Term,709.0,871112.0,2.0,Rent,Debt Consolidation,8391.73,12.5,10.0,0.0,38532.0,388036.0,0.0,0.0
3,3,83721ffb-b99a-4a0f-aea5-ef472a138b41,12116614-2f3c-4d16-ad34-d92883718806,176242.0,Short Term,727.0,780083.0,10.0,Rent,Debt Consolidation,16771.87,16.5,16.0,1.0,156940.0,531322.0,1.0,0.0
4,4,08f3789f-5714-4b10-929d-e1527ab5e5a3,39888105-fd5f-4023-860a-30a3e6f5ccb7,321992.0,Short Term,744.0,1761148.0,10.0,Home Mortgage,Debt Consolidation,39478.77,26.0,14.0,0.0,359765.0,468072.0,0.0,0.0

In [6]:
test_cleaned.tail(10)

,Unnamed: 0,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
9968,9990,91e26ead-810b-44a0-892f-d623e1e444a0,1e7cbdfe-d3a9-41a4-8416-3a23b08ef27b,260128.0,Long Term,611.00000,3.182519e+06,4.0,Home Mortgage,Debt Consolidation,79563.07,20.7,47.0,0.0,1398932.0,3673032.0,0.0,0.0
9969,9991,0594e01c-4230-4280-8267-78cd0c46f720,0c7d45a9-ff22-489c-82c0-073d74c46fd0,352704.0,Long Term,686.00000,9.138240e+05,3.0,Rent,Debt Consolidation,9595.19,9.0,5.0,0.0,299592.0,346214.0,0.0,0.0
9970,9992,4d0d0e65-e9aa-43e4-8de0-8aa2869a9983,add5361a-e612-4c58-bd7d-414543250ebc,428604.0,Long Term,697.00000,2.183043e+06,6.0,Home Mortgage,Debt Consolidation,16882.07,22.1,10.0,0.0,385187.0,525316.0,0.0,0.0
9971,9993,6f0b1e02-d222-4227-9161-b0c4fff4dd76,879d5bf4-6597-4f2b-ae7c-9deb68537c88,220858.0,Short Term,737.00000,1.234088e+06,NaN,Rent,Debt Consolidation,20362.49,9.5,10.0,0.0,273353.0,409442.0,0.0,0.0
9972,9994,a2701102-3cb0-46a6-8658-e6f20d950182,6dc5fa63-93f4-43a9-8192-2df57548287b,442596.0,Short Term,739.00000,1.528968e+06,7.0,Home Mortgage,Debt Consolidation,19494.38,16.7,11.0,0.0,419235.0,656876.0,0.0,0.0
9973,9995,c4ab66f9-833c-43b8-879c-4f8bcb64dd14,8ee2002b-8fb6-4af0-ab74-25a1c23e7647,157806.0,Short Term,731.00000,1.514376e+06,6.0,Rent,Debt Consolidation,4795.41,12.5,9.0,0.0,87058.0,234410.0,0.0,0.0
9974,9996,bbd3a392-01b4-4e0e-9c28-b2a4a39beac7,6c306306-f5c2-4db5-b74a-af2895123ecb,132550.0,Short Term,718.00000,7.631920e+05,4.0,Home Mortgage,Debt Consolidation,12401.87,9.9,8.0,0.0,74309.0,329692.0,0.0,0.0
9975,9997,da9870de-4280-46a3-8fc6-91cfe5bfde9d,cc94e25e-1060-4465-b603-194e122f0239,223212.0,Long Term,1078.84275,1.369940e+06,10.0,Rent,Debt Consolidation,4354.42,27.2,8.0,1.0,99636.0,568370.0,1.0,0.0
9976,9998,0cc8e0e0-1bc6-49d7-ad0f-0598b647458f,f90cf410-a34b-49e7-8af9-2b405e17b827,99999999.0,Short Term,721.00000,9.720970e+05,10.0,Home Mortgage,Debt Consolidation,12232.20,16.8,8.0,1.0,184984.0,240658.0,0.0,0.0
9977,9999,14f94b64-26c4-48fd-b916-1388d7adcc1d,f1838fa9-7ad9-44d5-97a6-7a6d3f3529d7,99999999.0,Short Term,748.00000,1.079960e+06,6.0,Home Mortgage,Debt Consolidation,12239.61,19.7,14.0,0.0,179018.0,607882.0,0.0,0.0

In [7]:
test_cleaned.shape

(9978, 18)

<font color='blue'>
<b>From above,


Shape ::

Train data-set : [99794,19]

Test data-set : [9978,18]
</b>

## Exploring and removing columns which are not important for analysis in the training and testing data-sets

In [9]:
train_cleaned.columns

Index(['Unnamed: 0', 'Loan ID', 'Customer ID', 'Loan Status',
       'Current Loan Amount', 'Term', 'Credit Score', 'Annual Income',
       'Years in current job', 'Home Ownership', 'Purpose', 'Monthly Debt',
       'Years of Credit History', 'Number of Open Accounts',
       'Number of Credit Problems', 'Current Credit Balance',
       'Maximum Open Credit', 'Bankruptcies', 'Tax Liens'],
      dtype='object')

In [12]:
test_cleaned.columns

Index(['Unnamed: 0', 'Loan ID', 'Customer ID', 'Current Loan Amount', 'Term',
       'Credit Score', 'Annual Income', 'Years in current job',
       'Home Ownership', 'Purpose', 'Monthly Debt', 'Years of Credit History',
       'Number of Open Accounts', 'Number of Credit Problems',
       'Current Credit Balance', 'Maximum Open Credit', 'Bankruptcies',
       'Tax Liens'],
      dtype='object')

<font color='blue'>
<b>From above, we can remove the columns ==>  'Unnamed: 0', 'Loan ID', 'Customer ID', as these are redudent and will not add anything to predictive analysis. Moreover, will add bias to the analysis.
</b>

In [13]:
train_cleaned.drop(columns=['Unnamed: 0', 'Loan ID', 'Customer ID'], axis=1, inplace=True)
test_cleaned.drop(columns=['Unnamed: 0', 'Loan ID', 'Customer ID'], axis=1, inplace=True)
train_cleaned.shape

(99794, 16)

In [14]:
test_cleaned.shape

(9978, 15)

In [16]:
train_cleaned.columns

Index(['Loan Status', 'Current Loan Amount', 'Term', 'Credit Score',
       'Annual Income', 'Years in current job', 'Home Ownership', 'Purpose',
       'Monthly Debt', 'Years of Credit History', 'Number of Open Accounts',
       'Number of Credit Problems', 'Current Credit Balance',
       'Maximum Open Credit', 'Bankruptcies', 'Tax Liens'],
      dtype='object')

In [15]:
test_cleaned.columns

Index(['Current Loan Amount', 'Term', 'Credit Score', 'Annual Income',
       'Years in current job', 'Home Ownership', 'Purpose', 'Monthly Debt',
       'Years of Credit History', 'Number of Open Accounts',
       'Number of Credit Problems', 'Current Credit Balance',
       'Maximum Open Credit', 'Bankruptcies', 'Tax Liens'],
      dtype='object')

<font color='blue'>
<b>From above, after removing the columns ==>  'Unnamed: 0', 'Loan ID', 'Customer ID'

Final Shape ::

Train data-set : [99794,16]

Test data-set : [9978,15]
</b>